### ISSUE TITLE
Unable to tame bats

### ISSUE THREAD

**Issue by ZenoMetal** [Fulmineo64/CompanionBats#1]
I play on a server with some friends, we all can't tame any bats. When right-clicking the bat with pumpkin pie, nothing happens and it is not consumed, but the mod is installed correctly as the items are craftable and show up in REI.
Minecraft version is 1.16.5

**Comment by ZenoMetal** [comment]
Oh sorry, I forgot to add that taming works just fine in singleplayer, it only won't work in multiplayer.

**Comment by Fulmineo64** [comment]
Hi ZenoMetal,
thank you for opening an issue.

Please make sure to have installed the mod both on the client and the server itself.

I'll be doing some checks myself in the meantime with the server version.

**Comment by ZenoMetal** [comment]
As I said, the mod IS installed correctly, clientside and serverside. Via commands and creative we were able to get the Companion Bat item, the issue is just that you are unable to tame Bats while on a server

**Comment by Fulmineo64** [comment]
Ok, it's fixed.
You can find the latest releases (1.0.6 and 1.1.2) here:
https://www.curseforge.com/minecraft/mc-mods/companion-bats/files

Thank you for the feedback!

**Comment by ZenoMetal** [comment]
Awesome, thanks a lot!
