### ISSUE TITLE
Bat Flute can Dissapear.

### ISSUE THREAD

**Issue by AmyMialee** [Fulmineo64/CompanionBats#10]
If the bat is too far away, in unloaded chunks, captured using something like a golden lasso, then using the flute will delete it. I cannot seem to find any way to get a new flute. This removal functionality should probably be removed or such.

**Comment by Akhnatan** [comment]
I second this as I am having the exact same issue.

**Comment by Fulmineo64** [comment]
Hi everyone. 

The latest version should fix this issue, now you'll receive a custom message instead of losing the flute.
Even if you lost it remember that you can re-tame your bat with some pumpkin pie!
The latest version comes also with custom flute names.

Bye!
