### ISSUE TITLE
Superflat generation bug prevents one from entering the world

### ISSUE THREAD

**Issue by Alluysl** [Fulmineo64/CompanionBats#12]
**Versions**
Minecraft: 1.17.1
Fabric loader: didn't ask the person, doesn't matter either way
Fabric API: 0.37.1
Companion Bats: 1.17.4
No other mods used

**Modloader**
Fabric

**Describe the bug**
Loading/creating an existing/new superflat world with the mod results in an error that prevents the world from being entered.

**To Reproduce**
1. Create new superflat world
2. You're greeted with an invalid datapacks error and an error in the logs (caused by trying to access the feature field of a ConfiguredStructureFeature which is null)
3. Choosing safe mode sends you back to the same screen

**Expected behavior**
The world loads properly as in vanilla, potentially with the feature

**Cause**
The Cave House is improperly registered in superflat worlds.

**Possible fix**
Superflat worlds require additional registry according to [this issue](https://github.com/b3spectacled/modern-beta-fabric/issues/32#issuecomment-876133474), either disable the feature there or perform said registry.
[This](https://github.com/b3spectacled/modern-beta-fabric/commit/90e0b35693205a65f96205cb71db62be9f0c8f5d) is the commit that fixed the issue in that mod, but I'm unaware if applying the same fix is possible or enough for features, though I just took a look at your initializer class and it seems pretty likely that it would work.

**Comment by Fulmineo64** [comment]
Hi Alluysl,
thank you for opening the issue.

As you can see helpimnotdrowning fixed it in a second!

You can find the fix in the latest release.

Many thanks to both of you for making the Companion Bats mod better!
