### ISSUE TITLE
Up to Lv 50

### ISSUE THREAD

**Issue by Anti27** [Fulmineo64/CompanionBats#15]
Hi, i think Bat level caps off way to early and even at max the bat is very weak (He still gets 1-shot by almost anything), so here is my idea:

(I hope you're fine with me giving ideas via issues)

[
	{ "totalExp": 0, "healthBonus": 0, "attackBonus": 0, "speedBonus": 0 },
	{ "totalExp": 50, "healthBonus": 1, "attackBonus": 0, "speedBonus": 0 },
	{ "totalExp": 150, "healthBonus": 2, "attackBonus": 0, "speedBonus": 0 },
	{ "totalExp": 300, "healthBonus": 2, "attackBonus": 0, "speedBonus": 0.03 },
	{ "totalExp": 500, "healthBonus": 2, "attackBonus": 1, "speedBonus": 0.03 },
	{ "totalExp": 750, "healthBonus": 3, "attackBonus": 1, "speedBonus": 0.03 },
	{ "totalExp": 1050, "healthBonus": 4, "attackBonus": 1, "speedBonus": 0.03 },
	{ "totalExp": 1400, "healthBonus": 4, "attackBonus": 1, "speedBonus": 0.06 },
	{ "totalExp": 1800, "healthBonus": 4, "attackBonus": 2, "speedBonus": 0.06 },
	{ "totalExp": 2250, "healthBonus": 5, "attackBonus": 2, "speedBonus": 0.06 },
	{ "totalExp": 2750, "healthBonus": 6, "attackBonus": 2, "speedBonus": 0.06 },
	{ "totalExp": 3300, "healthBonus": 6, "attackBonus": 2, "speedBonus": 0.09 },
	{ "totalExp": 3900, "healthBonus": 6, "attackBonus": 3, "speedBonus": 0.09 },
	{ "totalExp": 4550, "healthBonus": 7, "attackBonus": 3, "speedBonus": 0.09 },
	{ "totalExp": 5250, "healthBonus": 8, "attackBonus": 3, "speedBonus": 0.09 },
	{ "totalExp": 6000, "healthBonus": 8, "attackBonus": 3, "speedBonus": 0.12 },
	{ "totalExp": 6800, "healthBonus": 9, "attackBonus": 3, "speedBonus": 0.12 },
	{ "totalExp": 7650, "healthBonus": 10, "attackBonus": 3, "speedBonus": 0.12 },
	{ "totalExp": 8550, "healthBonus": 10, "attackBonus": 3, "speedBonus": 0.15 },
	{ "totalExp": 9550, "healthBonus": 10, "attackBonus": 4, "speedBonus": 0.15 },
	{ "totalExp": 10600, "healthBonus": 11, "attackBonus": 4, "speedBonus": 0.15 },
	{ "totalExp": 11700, "healthBonus": 12, "attackBonus": 4, "speedBonus": 0.15 },
	{ "totalExp": 13200, "healthBonus": 12, "attackBonus": 4, "speedBonus": 0.18 },
	{ "totalExp": 14950, "healthBonus": 12, "attackBonus": 5, "speedBonus": 0.18 },
	{ "totalExp": 16950, "healthBonus": 13, "attackBonus": 5, "speedBonus": 0.18 },
	{ "totalExp": 19000, "healthBonus": 14, "attackBonus": 5, "speedBonus": 0.18 },
	{ "totalExp": 21000, "healthBonus": 14, "attackBonus": 5, "speedBonus": 0.21 },
	{ "totalExp": 23000, "healthBonus": 14, "attackBonus": 6, "speedBonus": 0.21 },
	{ "totalExp": 25000, "healthBonus": 15, "attackBonus": 6, "speedBonus": 0.21 },
	{ "totalExp": 27500, "healthBonus": 16, "attackBonus": 6, "speedBonus": 0.21 },
	{ "totalExp": 30000, "healthBonus": 16, "attackBonus": 7, "speedBonus": 0.21 },
	{ "totalExp": 32500, "healthBonus": 16, "attackBonus": 7, "speedBonus": 0.24 },
	{ "totalExp": 35000, "healthBonus": 16, "attackBonus": 7, "speedBonus": 0.27 },
	{ "totalExp": 37500, "healthBonus": 17, "attackBonus": 7, "speedBonus": 0.27 },
	{ "totalExp": 40000, "healthBonus": 18, "attackBonus": 7, "speedBonus": 0.27 },
	{ "totalExp": 32500, "healthBonus": 18, "attackBonus": 8, "speedBonus": 0.27 },
	{ "totalExp": 35000, "healthBonus": 18, "attackBonus": 8, "speedBonus": 0.3 },
	{ "totalExp": 37500, "healthBonus": 19, "attackBonus": 8, "speedBonus": 0.3 },
	{ "totalExp": 40000, "healthBonus": 20, "attackBonus": 8, "speedBonus": 0.3 },
	{ "totalExp": 42500, "healthBonus": 20, "attackBonus": 9, "speedBonus": 0.3 },
	{ "totalExp": 45000, "healthBonus": 20, "attackBonus": 9, "speedBonus": 0.33 },
	{ "totalExp": 47500, "healthBonus": 20, "attackBonus": 10, "speedBonus": 0.33 },
	{ "totalExp": 50000, "healthBonus": 20, "attackBonus": 10, "speedBonus": 0.36 },
	{ "totalExp": 60000, "healthBonus": 22, "attackBonus": 11, "speedBonus": 0.39 },
	{ "totalExp": 70000, "healthBonus": 24, "attackBonus": 12, "speedBonus": 0.42 },
	{ "totalExp": 80000, "healthBonus": 26, "attackBonus": 13, "speedBonus": 0.45 },
	{ "totalExp": 90000, "healthBonus": 28, "attackBonus": 14, "speedBonus": 0.48 },
	{ "totalExp": 100000, "healthBonus": 30, "attackBonus": 15, "speedBonus": 0.5 },
	{ "totalExp": 150000, "healthBonus": 38, "attackBonus": 17, "speedBonus": 0.55 },
	{ "totalExp": 200000, "healthBonus": 46, "attackBonus": 20, "speedBonus": 0.6 }
]

**Comment by Fulmineo64** [comment]
See PR #18
