### ISSUE TITLE
Companion Bats don't seem to store some entity data

### ISSUE THREAD

**Issue by MoriyaShiine** [Fulmineo64/CompanionBats#2]
Particularly the UUID of the entity, though some other stuff may break. This can cause issues with Respawnable Pets, Bewitchment, and Origins (maybe), and any other mods that rely on a persistent entity uuid. I would recommend storing the entire bat entity to the bat item using Entity#saveSelfToTag(new CompoundTag()) to avoid any future problems.

**Comment by Fulmineo64** [comment]
Hi MoriyaShiine,
thanks for the info.

I really wouldn't want to use the **saveSelfToTag** if not absolutely necessary.
Although i'll give it a shot at keeping the persistent UUID.

I've already tried out Origins and Extra Origins with no apparent problems.
Respawnable Pets shouldn't be compatible to begin with, as the bat has its own death preventing system.
For the Bewitchment mod, unfortunately i haven't had the occasion to try it out yet.

Have you encountered some specific problems regarding the Bewitchment mod other than the UUID's one?
Which features of the Bewitchment mod rely on the UUID? (Asking for testing purposes) 

I'll be looking forward for your response.
For now, thanks for the feedback!

**Comment by MoriyaShiine** [comment]
Bewitchment relies on the uuid for familiars, and as any tamed mob can be your familiar, if the bat doesn't save the uuid then it locks you out of getting a new familiar forever. I also suggested making it store the whole entity for reasons such as if you curse a bat, or give it a status effect, or some other effect like that.

The origins issue I think would happen with origins classes, with the beastmaster perk

**Comment by Fulmineo64** [comment]
Hi, it's done.

I refactored completely the code to take advantage of Entity#saveSelfToTag.

It took a substantial amount of time to do, so I hope it will be worth the time in the end!

These changes will be published with a new release in the next few days.
The refactored code is available now on branch master.

I'm closing the issue for now but feel free to re-open it if the changes don't fully solve the problem.

Thank you for your feedback.
Have a nice day!
