### ISSUE TITLE
Feature request [activatable roosting mode] (Forge 1.16.5)

### ISSUE THREAD

**Issue by MAGGen-hub** [Fulmineo64/CompanionBats#21]
Why can't I let my bat go to the roosting mode by Shift-clicking on him? I mean if we click on wolf we can make him sit and FIX his position in the world... I want my bat to be in house and not leaving it until I say (shift-click on him again). You can do something like this in Pet Bat mod but well this mod only for 1.12.2 and lower.. 
Can you include this feature to your mod, please. I can try to make this feature and send you a pull request if you want. But now I have no time for it (Session soon). 
Thanks for your attantion... Hope you will add this (Well... I just like to see the bats on my ceiling. They looks cute =) )...
P.S. (If you don't understand how to do it try check other pet mods for 1.16 or Pet Bat mode source code)

**Comment by postal291** [comment]
The rest command from the flute should send your pet into roosting mode TBH, IMHO.
