### ISSUE TITLE
Curseforge files incorrect

### ISSUE THREAD

**Issue by itsdinkd** [Fulmineo64/CompanionBats#28]
![image](https://user-images.githubusercontent.com/35115304/215857179-bae77346-f176-4cd5-aaf3-bbd977461267.png)

Is it for 1.19.2, 1.19.3, or 1.19? shows different versions in three different spots.

**Comment by Fulmineo64** [comment]
Hi itsdinkd, 

back then i did a bit of chaos with the versions, now it should be fixed.

Bye!
